import type { Metadata } from "next";

interface MetadataOptions {
  title: string;
  description: string;
  path: string;
  /** Defaults to the site-wide card generated by `app/opengraph-image.tsx`. */
  imagePath?: string;
  publishedTime?: string;
}

/**
 * The `opengraph-image` file convention only covers the segment it sits in and
 * is not inherited by nested routes, and a page's `openGraph` object replaces
 * the root layout's rather than merging into it. So the default card has to be
 * named explicitly on every page.
 */
const DEFAULT_OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "THE GREEN CLOSETS — Sustainable style made easy",
};

/**
 * Builds page metadata with a canonical URL.
 *
 * URLs stay relative — the root layout sets `metadataBase`, so Next resolves
 * them against the deployment's origin. That keeps preview and production
 * deployments correct without threading the site URL through every caller.
 */
export const buildPageMetadata = ({
  title,
  description,
  path,
  imagePath,
  publishedTime,
}: MetadataOptions): Metadata => {
  const canonical = path.startsWith("/") ? path : `/${path}`;
  const image = imagePath ? { ...DEFAULT_OG_IMAGE, url: imagePath } : DEFAULT_OG_IMAGE;

  return {
    title,
    description,
    alternates: { canonical },
    openGraph: {
      title,
      description,
      url: canonical,
      images: [image],
      ...(publishedTime ? { type: "article", publishedTime } : {}),
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [image],
    },
  };
};
